name: Check New Pull Request
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image,js'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run tests
        run: |
          java --version
          mvn -B clean install
          cd tools/bamm-cli
          mvn -B -o verify -Pnative

      - name: Upload executable jar
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: bamm-cli.jar
          path: tools/bamm-cli/target/bamm-cli-*.jar

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-${{ matrix.os }}
          path: tools/bamm-cli/target/bamm.?e?x?e?
